classDiagram
    class Component {
        <<interface>>
        +operation() String
    }
    
    class RealComponent {
        +operation() String
    }
    
    class MessageDecorator {
        -Component component
        +MessageDecorator(Component component)
        +operation() String
    }
    
    class TimeDecorator {
        -Component component
        +TimeDecorator(Component component)
        +operation() String
    }
    
    class DecoratorPatternClient {
        -Component component
        +DecoratorPatternClient(Component component)
        +execute() void
    }
    
    Component <|.. RealComponent
    Component <|.. MessageDecorator
    Component <|.. TimeDecorator
    MessageDecorator --> Component
    TimeDecorator --> Component
    DecoratorPatternClient --> Component